const pattern_list = document.querySelector('#pattern-list');
const pattern_form = document.querySelector('#pattern-form');
const dictionary = ["he", "she", "his", "hers"];
const alpha = 26;
const pattern_input = document.querySelector('#pattern-input');
const delete_all = document.querySelector('#delete-all');
const text_to_check = document.querySelector('#text');
const text_form = document.querySelector('#text-form')
const text_input = document.querySelector('#text-input');